### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by BobyMCbobs** [ii/ii.nz#1]
Deploying a new ii.nz website to new infrastructure

# TODOs
- [x] cloudflare ii account created
- [x] balena ii account created
- [x] website repo to be set up
- [x] website to be deployed in fleet
- [x] document deployment steps and any other useful information
- [x] domain records to be served on cloudflare for [ii.nz](http://ii.nz/)
- [x] add caching?
- [x] cloudflare tunnels to be set up
- [x] balena var for cloudflare tunnels secret to be added
- [x] tunnel record pointed to ii.nz
- [x] new [ii.nz](http://ii.nz/) accessible and running the new site
- [x] peer-review on documentation

**Comment by BobyMCbobs** [comment]
The site is deployed!
